import type { Metadata } from "next";
import { InteriorIntro, InteriorOutro } from "@/components/interior-intro";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { academicExperience, industryExperience, type Experience, type Language } from "@/lib/site-content";

function Timeline({ id, title, items, lang }: { id: string; title: string; items: Experience[]; lang: Language }) { const tr = lang === "tr"; return <section id={id} className="timeline-block"><p className="section-index">{id === "academic" ? (tr ? "01 / AKADEMİ" : "01 / ACADEMIA") : (tr ? "02 / SEKTÖR" : "02 / INDUSTRY")}</p><h2>{title}</h2>{items.length ? <div className="timeline">{items.map((item) => <article className={item.current ? "timeline-current" : undefined} key={`${item.organization}-${item.period}`}><div><span>{item.period}</span>{item.current && <span className="current-label">{tr ? "Güncel" : "Current"}</span>}</div><div><h3>{item.role[lang]}</h3><h4>{item.organization}</h4><p>{item.description[lang]}</p></div></article>)}</div> : <div className="compact-empty">{tr ? "Doğrulanmış görev ve kurum bilgileri eklenecek." : "Verified role and institution details will be added."}</div>}</section>; }

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> { const { lang } = await params; const tr = lang === "tr"; return { title: tr ? "Deneyim" : "Experience", description: tr ? "Akademik ve sektör deneyimi." : "Academic and industry experience.", alternates: { languages: { en: "/en/experience", tr: "/tr/experience" } } }; }
export default async function ExperiencePage({ params }: { params: Promise<{ lang: string }> }) { const { lang: rawLang } = await params; if (rawLang !== "en" && rawLang !== "tr") notFound(); const lang = rawLang as Language; const tr = lang === "tr"; return <PageShell lang={lang}><main className="interior-page"><InteriorIntro lang={lang} eyebrow={tr ? "AKADEMİ VE SEKTÖR" : "ACADEMIA & INDUSTRY"} title={tr ? "Deneyim" : "Experience"} description={tr ? "Üniversite görevleri ile akademi dışı mühendislik ve teknoloji deneyimi. Araştırma, eğitim ve uygulamayı birbirine bağlayan bir mesleki yolculuk." : "University appointments alongside engineering and technology experience beyond academia. A professional journey connecting research, teaching, and practice."} visual="career" links={[{label:tr ? "Akademik deneyim" : "Academia",href:"#academic"},{label:tr ? "Sektör deneyimi" : "Industry",href:"#industry"}]} /><div className="shell experience-grid"><Timeline id="academic" title={tr ? "Akademik deneyim" : "Academic experience"} items={academicExperience} lang={lang} /><Timeline id="industry" title={tr ? "Sektör deneyimi" : "Industry experience"} items={industryExperience} lang={lang} /></div><InteriorOutro lang={lang} title={tr ? "Birlikte çalışalım." : "Let’s work together."} description={tr ? "Araştırma, eğitim ve teknoloji projeleri için iletişime geçebilirsiniz." : "Get in touch about research, education, and technology projects."} href={`/${lang}/contact`} label={tr ? "İletişime geç" : "Get in touch"} /></main></PageShell>; }
