import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { academicExperience, industryExperience, type Experience, type Language } from "@/lib/site-content";

function Timeline({ title, items, lang }: { title: string; items: Experience[]; lang: Language }) { const tr = lang === "tr"; return <section className="timeline-block"><h2>{title}</h2>{items.length ? <div className="timeline">{items.map((item) => <article key={`${item.organization}-${item.period}`}><div><span>{item.period}</span>{item.current && <span className="current-label">{tr ? "Güncel" : "Current"}</span>}</div><div><h3>{item.role[lang]}</h3><h4>{item.organization}</h4><p>{item.description[lang]}</p></div></article>)}</div> : <div className="compact-empty">{tr ? "Doğrulanmış görev ve kurum bilgileri eklenecek." : "Verified role and institution details will be added."}</div>}</section>; }

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> { const { lang } = await params; const tr = lang === "tr"; return { title: tr ? "Deneyim" : "Experience", description: tr ? "Akademik ve sektör deneyimi." : "Academic and industry experience.", alternates: { languages: { en: "/en/experience", tr: "/tr/experience" } } }; }
export default async function ExperiencePage({ params }: { params: Promise<{ lang: string }> }) { const { lang: rawLang } = await params; if (rawLang !== "en" && rawLang !== "tr") notFound(); const lang = rawLang as Language; const tr = lang === "tr"; return <PageShell lang={lang}><main><header className="page-hero shell"><p className="eyebrow">{tr ? "AKADEMİ VE SEKTÖR" : "ACADEMIA & INDUSTRY"}</p><h1>{tr ? "Deneyim" : "Experience"}</h1><p>{tr ? "Üniversite görevleri ile akademi dışı mühendislik ve teknoloji deneyimi." : "University appointments alongside engineering and technology experience beyond academia."}</p></header><div className="shell experience-grid"><Timeline title={tr ? "Akademik deneyim" : "Academic experience"} items={academicExperience} lang={lang} /><Timeline title={tr ? "Sektör deneyimi" : "Industry experience"} items={industryExperience} lang={lang} /></div></main></PageShell>; }
