import { publicationOverviews } from "@/lib/publication-overviews";

export type Language = "en" | "tr";
export type PublicationType = "article" | "conference" | "book" | "chapter";
type Bilingual = Record<Language, string>;

export type Publication = {
  id: string; title: string; authors: string[]; year: number; venue: string;
  type: PublicationType; doi?: string; openAccessUrl?: string; bibtex?: string;
  summary?: Bilingual; summaryKind?: "topic"; sourceUrl?: string; selected?: boolean;
};
export type Project = {
  slug: string; title: Bilingual; summary: Bilingual; problem: Bilingual;
  contribution: Bilingual; outcome?: Bilingual; period: string;
  status: "ongoing" | "completed"; kind: "academic" | "industry";
  links?: { label: string; href: string }[]; selected?: boolean;
};
export type Experience = { organization: string; role: Bilingual; period: string; description: Bilingual; current?: boolean };
export type Education = { institution: string; degree: Bilingual; field: Bilingual; period: string; thesis?: Bilingual };

export const researchAreas = [
  { id: "cybersecurity", title: { en: "Cybersecurity & Cryptography", tr: "Siber Güvenlik ve Kriptografi" }, description: { en: "Access governance, cryptographic systems, secure architectures, and institutional information security.", tr: "Erişim yönetişimi, kriptografik sistemler, güvenli mimariler ve kurumsal bilgi güvenliği." } },
  { id: "digital-evidence", title: { en: "Digital Evidence & Technology Law", tr: "Dijital Deliller ve Teknoloji Hukuku" }, description: { en: "Technical and legal reliability of digital evidence, data provenance, and auditable decision processes.", tr: "Dijital delillerin teknik ve hukuki güvenilirliği, veri kökeni ve denetlenebilir karar süreçleri." } },
  { id: "privacy", title: { en: "Privacy, Digital Governance & AI", tr: "Mahremiyet, Dijital Yönetişim ve Yapay Zekâ" }, description: { en: "Public digital services, privacy, trustworthy AI, accountability, and risk-aware governance.", tr: "Dijital kamu hizmetleri, mahremiyet, güvenilir yapay zekâ, hesap verebilirlik ve risk odaklı yönetişim." } },
  { id: "information-systems", title: { en: "Information Systems & Technology Projects", tr: "Bilgi Sistemleri ve Teknoloji Projeleri" }, description: { en: "Large-scale ICT infrastructures, capability assessment, digital transformation, and applied R&D.", tr: "Büyük ölçekli BT altyapıları, yetkinlik değerlendirmesi, dijital dönüşüm ve uygulamalı Ar-Ge." } },
] as const;

const publicationRecords: Publication[] = [
  { id: "dual-key-2026", title: "Dual Key-Wrapping Architecture for Query-Level Cryptographic Access Governance of Protected Digital Records in Institutional Information Systems", authors: ["Hakan Yıldırım"], year: 2026, venue: "Acta Infologica", type: "article", selected: true, summary: { en: "Proposes a dual key-wrapping architecture that keeps protected records encrypted by default and authorizes narrowly scoped queries instead of broad database access. Prototype scenarios test separation of privileged roles, personal and lawful access paths, data minimization, and tamper-resistant auditing.", tr: "Korunan kayıtları varsayılan olarak şifreli tutan ve geniş veritabanı yetkileri yerine amaç ve kapsamla sınırlandırılmış sorguları yetkilendiren çift anahtar sarma mimarisi önerir. Prototip senaryolar; ayrıcalıklı rollerin ayrılmasını, kişisel ve hukuki erişim yollarını, veri minimizasyonunu ve denetim izlerini sınar." } },
  { id: "digital-risk-2026", title: "Digital Risk Perceptions and Trust-Enhancing Governance in Türkiye: Evidence from Public Digital-Service Users", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2026, venue: "Ethics and Information Technology", type: "article", selected: true, summary: { en: "Examines how users of highly digitized public services perceive risks and which safeguards they believe would strengthen trust. Survey findings show that frequent use does not eliminate concern, while sanctions, contestability, independent oversight, transparency, and effective redress remain central to trusted governance.", tr: "Yoğun dijital kamu hizmeti kullanan kişilerin risk algısını ve güveni artıracağını düşündükleri güvenceleri inceler. Bulgular, sık kullanımın kaygıyı ortadan kaldırmadığını; yaptırım, itiraz edebilme, bağımsız denetim, şeffaflık ve etkili başvuru yollarının güvenilir yönetişim için merkezî olduğunu gösterir." } },
  { id: "chip-crypto-2026", title: "Assessing security and legal reliability in chip-based cryptographic systems: a normative assessment framework", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2026, venue: "Cyber Security", type: "article", summary: { en: "Develops a framework linking cryptographic security to transparency, verifiability, auditability, source reliability, and proportionality. Its application to identity, passport, signature, payment, and SIM systems suggests that closed implementation layers can limit legal reliability even when cryptographic primitives are strong.", tr: "Kriptografik güvenliği şeffaflık, doğrulanabilirlik, denetlenebilirlik, kaynak güvenilirliği ve ölçülülükle ilişkilendiren bir çerçeve geliştirir. Kimlik, pasaport, imza, ödeme ve SIM sistemlerine uygulama; güçlü kriptografiye rağmen kapalı uygulama katmanlarının hukuki güvenilirliği sınırlayabildiğini gösterir." } },
  { id: "toxic-databases-2026", title: "Zehirli Veritabanları: Kurumsal Veri Sistemlerinde Hukuki, Teknik-Bilgisel ve Yönetişimsel Güvenilirliğin Değerlendirilmesine Yönelik Karşılaştırmalı Bir Çerçeve", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2026, venue: "Ankara Sosyal Bilimler Üniversitesi Bilişim Hukuku Dergisi", type: "article", summary: { en: "Introduces the concept of a ‘toxic database’ to explain how initially lawful and accurate data systems can lose reliability through their lifecycle. The model traces legal, technical, and governance defects across collection, transfer, combination, inference, retention, and decision-making.", tr: "Başlangıçta hukuka uygun ve doğru olan veri sistemlerinin yaşam döngüsü içinde güvenilirliğini nasıl yitirebildiğini açıklamak için “zehirli veritabanı” kavramını önerir. Model; toplama, aktarım, birleştirme, türetme, saklama ve karar aşamalarındaki hukuki, teknik ve yönetişimsel sorunları izler." } },
  { id: "digital-evidence-2026", title: "Dijital Delillerde Güvenin İnşası: Delil Toplama ve Değerlendirme Süreçleri İçin 5K1N Temelli Bir Hukuki İndeks Önerisi", authors: ["Ramazan Yıldırım", "Hakan Yıldırım", "Cihan Ünal"], year: 2026, venue: "İzmir Barosu Dergisi, 91(2), 137–162", type: "article", openAccessUrl: "https://www.izmirbarosu.org.tr/Yayin/2362/sayi-2026-2", summary: { en: "Reframes 5W1H as a six-part index for evaluating how digital evidence is produced, protected, recorded, and justified. It connects authentication, confidentiality, integrity, non-repudiation, accountability, and governance to practical questions for investigators, prosecutors, judges, and counsel.", tr: "5K1N yaklaşımını dijital delilin nasıl üretildiğini, korunduğunu, kayda geçirildiğini ve gerekçelendirildiğini değerlendiren altı boyutlu bir indekse dönüştürür. Kimlik doğrulama, gizlilik, bütünlük, inkâr edilemezlik, hesap verebilirlik ve yönetişimi soruşturma ve yargılama süreçlerinde kullanılabilecek sorularla ilişkilendirir." } },
  { id: "minority-report-2026", title: "Minority Report’tan Palantir’e: Probabilistik İstihbarat Analizlerinin Delil Hukuku Açısından Değerlendirilmesi", authors: ["Hakan Yıldırım"], year: 2026, venue: "Hacettepe Üniversitesi Edebiyat Fakültesi Dergisi", type: "article" },
  { id: "ai-judgment-2026", title: "Yapay Zekâ Hüküm Kurabilir mi? Algoritmik Delillerin Tiranlığı", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2026, venue: "İzmir Barosu Dergisi", type: "article" },
  { id: "ai-surveillance-2026", title: "Yapay Zekâ Destekli Gözetim Sistemlerinde Mahremiyet Tehlikesi", authors: ["Hakan Yıldırım"], year: 2026, venue: "Türkiye Sosyal Araştırmalar Dergisi", type: "article" },
  { id: "signalgate-2026", title: "Encrypted but Still Vulnerable? A Case Study of the 2025 ‘SignalGate’ Incident and the Limits of End-to-End Encryption", authors: ["Cihan Ünal", "Hakan Yıldırım"], year: 2026, venue: "Kamu Ekonomisi ve Kamu Mali Yönetimi Dergisi", type: "article" },
  { id: "crypto-tracing-2025", title: "Kripto Para İşlemlerinin İzlenmesinde Mali İstihbarat Birimlerinin Karşılaştığı Zorluklar ve Yeni Stratejiler", authors: ["Cihan Ünal", "Hakan Yıldırım"], year: 2025, venue: "Acta Infologica, 9(2), 562–579", type: "article", doi: "10.26650/acin.1598844" },
  { id: "uyap-2025", title: "UYAP’ın Holistik Güvenlik Denetimi", authors: ["Hakan Yıldırım"], year: 2025, venue: "Denetişim, 16(32), 189–203", type: "article", doi: "10.58348/denetisim.1532057" },
  { id: "industry4-2024", title: "CMMI 4–5 Seviyelerinde Olan BT Şirketlerinin Endüstri 4.0’a Hazırlık Durumları: Sistematik Bir Değerlendirme ve Ölçüm Yaklaşımı", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2024, venue: "Mühendis ve Makina, 65(717), 717–742", type: "article", doi: "10.46399/muhendismakina.1456837" },
  { id: "academics-ai-2024", title: "Türkiye’deki Akademisyenlerin Yapay Zekâ (YZ) Ürünlerini (Uygulama ve Araçlarını) Kullanımları Hakkında Bir Araştırma", authors: ["Cihan Ünal", "Hakan Yıldırım"], year: 2024, venue: "Sinop Üniversitesi Fen Bilimleri Dergisi, 9(1), 128–144", type: "article", doi: "10.33484/sinopfbd.1434171" },
  { id: "maturity-2022", title: "Application of the Maturity Model in Industrial Corporations", authors: ["Hakan Yıldırım", "Cihan Ünal", "Cemil Sungur"], year: 2022, venue: "Sustainability, 14, 9478", type: "article", doi: "10.3390/su14159478" },
  { id: "cybersecurity-expertise-2026", title: "Siber Güvenlik Uzmanlığı", authors: ["Hakan Yıldırım"], year: 2026, venue: "Novarge · 1. Baskı · 458 sayfa · ISBN 978-625-00-5951-7", type: "book" },
  { id: "cybersecurity-guide-2025", title: "Siber Güvenlik Rehberi — Tehditten Çözüme", authors: ["Hakan Yıldırım", "Cihan Ünal"], year: 2025, venue: "Nobel Akademik · 230 sayfa · ISBN 978-625-386-484-2 · eISBN 978-625-386-485-9", type: "book", selected: true },
  { id: "meclis-2021", title: "Meclis-i Mahfuzan", authors: ["Hakan Yıldırım"], year: 2021, venue: "Macar Publishing House · 114 sayfa · ISBN 978-605-74689-0-1", type: "book" },
  { id: "e-devlet-2006", title: "E-Devlet Başa", authors: ["Hakan Yıldırım", "Volkan Kaplan"], year: 2006, venue: "İmyay Yayıncılık · 238 sayfa · ISBN 975-98401-2-X", type: "book" },
  { id: "polisce-2005", title: "PolisCE", authors: ["Hakan Yıldırım"], year: 2005, venue: "Macar Publishing · 203 sayfa · ISBN 975-98401-0-3", type: "book" },
  { id: "police-2004", title: "PoliCE", authors: ["Hakan Yıldırım"], year: 2004, venue: "Macar Publishing · English edition · 198 pages · ISBN 975-98401-1-1", type: "book" },
  { id: "elestirdik-2002", title: "Her Şeyi E-leştirdik", authors: ["Hakan Yıldırım"], year: 2002, venue: "Macar Publishing · 467 sayfa · ISBN 975-288-287-0", type: "book" },
  { id: "document-privacy-2026", title: "Belge ve Mahremiyet", authors: ["Hakan Yıldırım", "Cihan Ünal", "Ramazan Yıldırım"], year: 2026, venue: "Belge Yönetimi Kitabı · 20 sayfa", type: "chapter" },
  { id: "basic-it-2024", title: "İnternet Teknolojileri; E-Devlet Uygulamaları; Bilgisayar Ağ Güvenliği", authors: ["Hakan Yıldırım"], year: 2024, venue: "Temel Bilgi Teknolojileri 1–2 · Nobel Akademik · ISBN 978-625-371-659-2", type: "chapter" },
];

export const publications: Publication[] = publicationRecords.map((publication) => ({
  ...publication,
  ...publicationOverviews[publication.id],
}));

const project = (slug: string, title: Bilingual, period: string, status: "ongoing" | "completed", kind: "academic" | "industry", summary: Bilingual, problem: Bilingual, contribution: Bilingual, selected = false, outcome?: Bilingual): Project => ({ slug, title, period, status, kind, summary, problem, contribution, selected, outcome });
export const projects: Project[] = [
  project("polnet", { en: "POLNET — National Police Network", tr: "POLNET — Polis Bilgi Ağı" }, "1996–2005", "completed", "industry", { en: "A nationwide information and communication network for police services.", tr: "Emniyet hizmetleri için ülke çapında bilgi ve iletişim ağı." }, { en: "Police units needed a shared, secure national infrastructure for operational information and communication.", tr: "Emniyet birimlerinin operasyonel bilgi ve iletişim için ortak ve güvenli bir ulusal altyapıya ihtiyacı vardı." }, { en: "Served as project leader throughout planning, implementation, and operation.", tr: "Planlama, uygulama ve işletim süreçlerinde proje lideri olarak görev aldı." }, true, { en: "Established an integrated national network connecting police information services.", tr: "Emniyet bilgi hizmetlerini bütünleştiren ulusal ağ altyapısı kuruldu." }),
  project("afis", { en: "AFIS — Automated Fingerprint Identification System", tr: "AFIS — Otomatik Parmak İzi Teşhis Sistemi" }, "1998–2002", "completed", "industry", { en: "Development and deployment of automated fingerprint identification.", tr: "Otomatik parmak izi teşhis yeteneğinin geliştirilmesi ve devreye alınması." }, { en: "Fingerprint records required faster, consistent matching at operational scale.", tr: "Parmak izi kayıtlarının operasyonel ölçekte hızlı ve tutarlı biçimde eşleştirilmesi gerekiyordu." }, { en: "Led the technical and operational implementation.", tr: "Teknik ve operasyonel uygulamada proje liderliği yaptı." }),
  project("metsis", { en: "METSİS — Parliamentary ICT Infrastructure", tr: "METSİS — TBMM Bilişim Altyapısı" }, "2007–2009", "completed", "industry", { en: "A comprehensive ICT infrastructure program for the Turkish Grand National Assembly.", tr: "Türkiye Büyük Millet Meclisi için bütüncül bilişim altyapısı programı." }, { en: "Parliamentary services required an integrated, manageable, and secure ICT foundation.", tr: "Meclis hizmetleri için bütünleşik, yönetilebilir ve güvenli bir BT temeli gerekiyordu." }, { en: "Served as project leader for the institution-wide program.", tr: "Kurum genelindeki programda proje lideri olarak görev aldı." }, true),
  project("istanbul-mobese", { en: "İstanbul MOBESE", tr: "İstanbul MOBESE" }, "2004–2006", "completed", "industry", { en: "Urban security and electronic monitoring infrastructure for İstanbul.", tr: "İstanbul için kent güvenliği ve elektronik izleme altyapısı." }, { en: "Urban security operations required coordinated monitoring and communication systems.", tr: "Kent güvenliği operasyonları eşgüdümlü izleme ve iletişim sistemleri gerektiriyordu." }, { en: "Led the project during implementation.", tr: "Uygulama döneminde proje liderliğini yürüttü." }),
  project("smart-pos", { en: "Smart POS and E-Invoice Conversion", tr: "Yeni Nesil POS ve E-Fatura Dönüşümü" }, "2019", "completed", "academic", { en: "TÜBİTAK 1507 project 7190116 on converting cash register/POS systems to e-invoicing.", tr: "Ödeme kaydedici/POS sistemlerinin e-faturaya dönüşümünü ele alan TÜBİTAK 1507 projesi (7190116)." }, { en: "Retail devices needed a compliant path to electronic invoicing.", tr: "Perakende cihazlarının elektronik faturalamaya uyumlu dönüşümü gerekiyordu." }, { en: "Contributed as project advisor.", tr: "Proje danışmanı olarak katkı sundu." }),
  project("electronic-market-basket", { en: "Electronic Market Basket Smart Shopping Platform", tr: "Elektronik Market Sepeti Akıllı Alışveriş Platformu" }, "2019–", "ongoing", "academic", { en: "A TÜBİTAK-supported smart shopping platform.", tr: "TÜBİTAK destekli akıllı alışveriş platformu." }, { en: "Explores a more connected and efficient in-store shopping flow.", tr: "Mağaza içi alışveriş akışını daha bağlantılı ve verimli hâle getirmeyi ele alır." }, { en: "Listed among ongoing TÜBİTAK assignments in the CV.", tr: "CV’de devam eden TÜBİTAK görevleri arasında yer almaktadır." }),
  project("prostate-cancer", { en: "Prostate Cancer Decision Support", tr: "Prostat Kanseri Karar Destek Sistemi" }, "2020–2022", "completed", "academic", { en: "TÜBİTAK 1501 project 3191419 for early diagnosis and treatment decision support.", tr: "Erken teşhis ve tedavi kararı desteği için TÜBİTAK 1501 projesi (3191419)." }, { en: "Clinical teams needed structured computer-aided diagnostic support.", tr: "Klinik ekiplerin yapılandırılmış bilgisayar destekli tanı desteğine ihtiyacı vardı." }, { en: "Served as project advisor.", tr: "Proje danışmanı olarak görev aldı." }, true),
  project("ask-another-doctor", { en: "Ask Another Doctor", tr: "Bir Doktora Daha Sor" }, "2021–", "ongoing", "academic", { en: "A TÜBİTAK project for digitally supported access to an additional medical opinion.", tr: "Ek bir tıbbi görüşe dijital destekle erişmeyi amaçlayan TÜBİTAK projesi." }, { en: "Patients need a structured way to request and manage another clinical opinion.", tr: "Hastaların başka bir klinik görüşü talep edip yönetebileceği yapılandırılmış bir sürece ihtiyacı vardır." }, { en: "Serves as project leader.", tr: "Proje lideri olarak görev yapmaktadır." }),
  project("kec", { en: "KEC — Identity Card Verification Device", tr: "KEC — Kimlik Kartı Erişim ve Doğrulama Cihazı" }, "2019–", "ongoing", "academic", { en: "A TÜBİTAK project developing an identity-card access and verification device.", tr: "T.C. kimlik kartına erişim ve doğrulama cihazı geliştiren TÜBİTAK projesi." }, { en: "Organizations need dependable hardware-assisted identity verification.", tr: "Kurumların güvenilir, donanım destekli kimlik doğrulamasına ihtiyacı vardır." }, { en: "Listed among ongoing TÜBİTAK assignments in the CV.", tr: "CV’de devam eden TÜBİTAK görevleri arasında yer almaktadır." }),
  project("iot-logistics", { en: "IoT Logistics Optimization Portal", tr: "IoT Lojistik Optimizasyon Portalı" }, "2019–", "ongoing", "academic", { en: "A web and mobile portal using IoT data for load, route, and courier optimization.", tr: "Yük, rota ve kurye optimizasyonu için IoT verilerini kullanan web ve mobil portal." }, { en: "Food distribution networks must coordinate resources under changing conditions.", tr: "Gıda dağıtım ağlarının değişen koşullarda kaynakları eşgüdümlemesi gerekir." }, { en: "Contributed within the documented TÜBİTAK project assignment.", tr: "Belgelenen TÜBİTAK proje görevi kapsamında katkı sundu." }),
  project("endoscopic-diagnosis", { en: "Endoscopic Image-Based Cancer Diagnosis", tr: "Endoskopik Görüntü Tabanlı Kanser Tanısı" }, "2019–2021", "completed", "academic", { en: "TÜBİTAK 1501 project 3190472 for early diagnosis using endoscopic and colonoscopic images.", tr: "Endoskopik ve kolonoskopik görüntülerle erken tanı geliştiren TÜBİTAK 1501 projesi (3190472)." }, { en: "Image-based assessment can benefit from consistent computer-assisted support.", tr: "Görüntü temelli değerlendirme tutarlı bilgisayar desteğinden yararlanabilir." }, { en: "Served as project advisor.", tr: "Proje danışmanı olarak görev aldı." }),
];

export const academicExperience: Experience[] = [
  { organization: "Çankaya University · Computer Engineering", role: { en: "Part-Time Faculty Member", tr: "Yarı Zamanlı Öğretim Üyesi" }, period: "Jun 2026–", current: true, description: { en: "Teaching and academic work in the English-medium Computer Engineering program.", tr: "İngilizce Bilgisayar Mühendisliği programında ders ve akademik çalışmalar." } },
  { organization: "Ankara Science University · Computer Engineering", role: { en: "Assistant Professor", tr: "Doktor Öğretim Üyesi" }, period: "2024–2025", description: { en: "Taught cybersecurity and IT governance in the English-medium program.", tr: "İngilizce programda siber güvenlik ve BT yönetişimi dersleri verdi." } },
  { organization: "Beykent University · Computer Engineering", role: { en: "Assistant Professor", tr: "Doktor Öğretim Üyesi" }, period: "2022–2023", description: { en: "Academic appointment in Computer Engineering.", tr: "Bilgisayar Mühendisliği programında akademik görev." } },
  { organization: "Antalya AKEV University · Yacht Captain Program", role: { en: "Assistant Professor", tr: "Doktor Öğretim Üyesi" }, period: "2021", description: { en: "Academic appointment in Transportation Services.", tr: "Ulaştırma Hizmetleri programında akademik görev." } },
  { organization: "Antalya AKEV University · Management Information Systems", role: { en: "Assistant Professor", tr: "Doktor Öğretim Üyesi" }, period: "2020", description: { en: "Academic appointment in Management Information Systems.", tr: "Yönetim Bilişim Sistemleri bölümünde akademik görev." } },
  { organization: "OSTİM Technical University · Information Security Technology", role: { en: "Assistant Professor", tr: "Doktor Öğretim Üyesi" }, period: "2019–2020", description: { en: "Academic appointment in Information Security Technology.", tr: "Bilgi Güvenliği Teknolojisi programında akademik görev." } },
];
export const industryExperience: Experience[] = [
  { organization: "Novarge AŞ", role: { en: "Masterclass Instructor", tr: "Masterclass Eğitmeni" }, period: "Sep 2025–", current: true, description: { en: "Designs and delivers programs in cybersecurity, IT, digital transformation, and information security.", tr: "Siber güvenlik, BT, dijital dönüşüm ve bilgi güvenliği programları tasarlayıp sunar." } },
  { organization: "Turkish Grand National Assembly", role: { en: "Advisor / Deputy Head Responsible for IT", tr: "Müşavir / Bilgi İşlemden Sorumlu Başkan Yardımcısı" }, period: "2007–2024", description: { en: "Held senior responsibility for information-processing services and technology infrastructure.", tr: "Bilgi işlem hizmetleri ve teknoloji altyapısında üst düzey sorumluluk üstlendi." } },
  { organization: "Navtürk", role: { en: "Deputy General Manager, Navigation Systems", tr: "Genel Müdür Yardımcısı, Navigasyon Sistemleri" }, period: "2006–2007", description: { en: "Managed navigation-system development work.", tr: "Navigasyon sistemleri geliştirme çalışmalarını yönetti." } },
  { organization: "Ministry of Interior", role: { en: "ICT and Communications Networks Specialist", tr: "Bilgi ve İletişim Teknolojileri Sorumlusu" }, period: "1996–2006", description: { en: "Worked on ICT and nationwide communications networks.", tr: "BT ve ülke çapındaki haberleşme ağları üzerinde çalıştı." } },
];
export const education: Education[] = [
  { institution: "Piri Reis University", degree: { en: "PhD", tr: "Doktora" }, field: { en: "Maritime Transportation Management Engineering", tr: "Deniz Ulaştırma İşletme Mühendisliği" }, period: "2012–2018", thesis: { en: "The application of shipbuilding managerial and operational capability assessment model (S-MCM) to Turkish shipyards", tr: "Gemi inşa yönetimsel ve operasyonel yetkinlik değerlendirme modelinin (S-MCM) Türk tersanelerine uygulanması" } },
  { institution: "Police Academy", degree: { en: "Master’s", tr: "Yüksek Lisans" }, field: { en: "Transportation Security and Management", tr: "Ulaşım Güvenliği ve Yönetimi" }, period: "2010–2012", thesis: { en: "Analysis of physical and virtual security perception among the employees of the Turkish Grand National Assembly", tr: "Fiziksel ve sanal güvenlik algısının TBMM çalışanları açısından analizi" } },
  { institution: "Middle East Technical University", degree: { en: "BSc", tr: "Lisans" }, field: { en: "Electrical and Electronic Engineering", tr: "Elektrik-Elektronik Mühendisliği" }, period: "1989–1997" },
];
export const profile = {
  name: "Dr. Hakan Yıldırım",
  title: { en: "Part-Time Faculty Member · Computer Engineering", tr: "Yarı Zamanlı Öğretim Üyesi · Bilgisayar Mühendisliği" },
  email: "hakanyildirim72@gmail.com",
  cvPath: "/hakan-yildirim-cv.pdf",
  links: [
    { label: "ORCID", href: "https://orcid.org/0000-0002-5959-2691" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/hakan-yildirim-phd-599853197/" },
  ],
};
